#ifndef X_COM_H
#define X_COM_H
#include <x_globals.h>
enum RESULT {SUCCESS, FAILURE};
enum X_COMMAND
{
  X_COM_FIRST= 0,
  X_COM_SLEEP= 0,
  X_COM_QUIT,
  X_COM_INIT_DB,
  X_COM_QUERY,
  X_COM_FIELD_LIST,
  X_COM_CREATE_DB,
  X_COM_DROP_DB,
  X_COM_REFRESH,
  X_COM_SHUTDOWN,
  X_COM_STATISTICS,
  X_COM_PROCESS_KILL,
  X_COM_PING,
  X_COM_TIME,
  X_COM_DELAYED_INSERT,
  X_COM_CHANGE_USER,
  X_COM_BINLOG_DUMP,
  X_COM_TABLE_DUMP,
  X_COM_CONNECT_OUT,
  X_COM_REGISTER_SLAVE,
  X_COM_STMT_PREPARE,
  X_COM_STMT_EXECUTE,
  X_COM_STMT_SEND_LONG_DATA,
  X_COM_STMT_CLOSE,
  X_COM_STMT_RESET,
  X_COM_SET_OPTION,
  X_COM_STMT_FETCH,
  X_COM_DAEMON,
  X_COM_BINLOG_DUMP_GTID,
  X_COM_END
};

X_COMMAND get_server_command(int com_val);
#endif
